MARKET: SNP

LOGLEVEL: ERROR

MAXDTE: 50
PUTSTDMULT: 1.44
CALLSTDMULT: 1.59
MINEXPROM: 3.5
MARGINPERORDER: 10000
CCCCP_MAX_DTE: 30 # Covered Call and Cash Covered Put max dte
CCCCP_STDMULT: 0.8 # CC and CCP standard deviation multiple

# NSE ports and client IDs
PORT: 1300
PAPER: 1301

CID: 10

  


